### ISSUE TITLE
Exported HAR works in 0.14.6 but not 1.0.0-1.0.2, cannot import name 'TaskSequence'

### ISSUE THREAD

**Issue by TimSC** [zalando-incubator/transformer#69]
My exported HAR file has this error on locust 1.0.2 but works fine in 0.14.6:

```(venv) tim@helium ~/dev/qbrio-load $ locust -f locustfile.py 
Traceback (most recent call last):
  File "/home/tim/dev/qbrio-load/venv/bin/locust", line 11, in <module>
    sys.exit(main())
  File "/home/tim/dev/qbrio-load/venv/lib/python3.6/site-packages/locust/main.py", line 113, in main
    docstring, user_classes = load_locustfile(locustfile)
  File "/home/tim/dev/qbrio-load/venv/lib/python3.6/site-packages/locust/main.py", line 77, in load_locustfile
    imported = __import_locustfile__(locustfile, path)
  File "/home/tim/dev/qbrio-load/venv/lib/python3.6/site-packages/locust/main.py", line 53, in __import_locustfile__
    return  source.load_module()
  File "<frozen importlib._bootstrap_external>", line 399, in _check_name_wrapper
  File "<frozen importlib._bootstrap_external>", line 823, in load_module
  File "<frozen importlib._bootstrap_external>", line 682, in load_module
  File "<frozen importlib._bootstrap>", line 265, in _load_module_shim
  File "<frozen importlib._bootstrap>", line 684, in _load
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/tim/dev/qbrio-load/locustfile.py", line 5, in <module>
    from locust import TaskSequence
ImportError: cannot import name 'TaskSequence'```

**Comment by thilp** [comment]
Hi @TimSC, thank you for reporting this!

I see in [Locust's "Changelog Highlights", under _Other breaking changes_][changelog]:
> `TaskSequence` and `@seq_task` has been replaced with `SequentialTaskSet`.

[changelog]: https://docs.locust.io/en/latest/changelog.html#other-breaking-changes

As a quick fix, we can probably add code (in the generated locustfile) that checks Locust's version and aborts with a more helpful message if Locust v1+ is detected.

Longer term, we need to either decide to only support one major version of Locust (probably the latest), or a mechanism to support multiple major versions (e.g. with command-line switches).
I think I'm personally in favor of the first option, but I would be very interested to know what you think @tortila and @TimSC.

**Comment by tortila** [comment]
Thanks for pinging me, @thilp! 

I like your idea for the quick fix.

I'm fine with supporting only the most recent major version of Locust long-term. We could consider releasing a new major version of Transformer to designate this breaking change (supporting Locust 1.0+). Not sure if this is a good practice, but seems like a valid option. 

I see that we have Locust as a dev dependency for Transformer. Do you remember, @thilp, what was it used for? Does it make sense to also limit the version to <1.0 there?

**Comment by thilp** [comment]
Since Locust (and Transformer) are more tools than libraries, I think it's safe to assume that people always have the opportunity to use their latest version, so releasing a new major version of Transformer coupled with the new major version of Locust sounds like a good idea.

I think the dev dependency on Locust in Transformer is both a way to easily get a Locust to manually test Transformer, and helps with autocomplete in IDEs like PyCharm that inspect imports. Today, I'd rather install Locust using pipx to get the same experience as most people who probably also did a "pip/pipx install locust", so the "manual test" use case seems obsolete, but for the "autocomplete" use case it's probably best to keep the dev dependency of Locust at the same major version as the one supported by Transformer. Thank you for pointing this out!

**Comment by TimSC** [comment]
Supporting both versions of locust might be good, at least in the short term. If they break more things, it might be time to review.

**Comment by tortila** [comment]
@TimSC the newly released Transformer 1.2.7 fixes the issue you reported by only supporting "old" Locust versions (like 0.14.6). Soon we will release a new Transformer version that will be compatible with Locust 1.0+ where `TaskSequence` was replaced with `SequentialTaskSet`. I agree with you that the support of both Locust versions can be decided later in the future, depending on any new issues that are discovered in Transformer or its integration with Locust.

**Comment by thilp** [comment]
Here is the (abbreviated) diff showing what should change in today's generated locustfiles to support Locust 1.0.2, on our real-world "zalando" example:

```diff
4,7c4,5
< from locust import HttpLocust
< from locust import TaskSequence
< from locust import TaskSet
< from locust import seq_task
---
> from locust import HttpUser
> from locust import SequentialTaskSet
9,11c7,9
< class examples_en_zalando_de_har_2286422489(TaskSequence):
<     @seq_task(1)
<     def GET_https_www_zalando_de_710411636___3145776_7423683142028648499(self):
---
> class examples_en_zalando_de_har_2286422489(SequentialTaskSet):
>     @task
>     def GET_https_www_zalando_de_710411636___3145776_3463505882896678350(self):
235,236c233,234
< class LocustForexamples_en_zalando_de_har_2286422489(HttpLocust):
<     task_set = examples_en_zalando_de_har_2286422489
---
> class LocustForexamples_en_zalando_de_har_2286422489(HttpUser):
>     tasks = [examples_en_zalando_de_har_2286422489]
```
Summary:
1. _TaskSequence_ is replaced with _SequentialTaskSet_.
1. `@seq_task(N)` is replaced with `@task`.
1. _HttpLocust_ is replaced with _HttpUser_.
1. `task_set` (expecting a class) is replaced with `tasks` (expecting a list of classes).

At least that's what was necessary to make Locust happy with the locustfile; I didn't actually check that it was sending traffic when starting a load test.

It looks like we could easily support both major versions of Locust by aliasing _TaskSequence_ as _SequentialTaskSet_, make `seq_task` ignore its argument and alias it to `task`, aliasing _HttpLocust_ as _HttpUser_ and providing both `task_set` and `tasks` fields; this wouldn't lead to completely duplicated code as I initially feared. However, with this approach, we risk missing something so more complex locustfiles might still not work properly with recent Locust versions; and if Locust adds more breaking changes (compared to <1.0), we might not be able to keep up with simple fixes like the conditional aliasing I proposed. The approach still has the benefit that people using Transformer regularly will hopefully get a deprecation warning about updating their Locust version before Transformer totally stops working with older Locusts.

With that in mind, I would recommend to deprecate (but not remove yet) support for Locust <1.0 in the next Transformer release. Since Transformer is not a library (at least I've no knowledge of anyone using it that way), and it's using semver, I think it's safe to also bump its major version like @tortila suggested when we remove support for Locust <1.0. It's a small project, so I don't think it's reasonable to take on the task of supporting multiple incompatible versions of a dependency on which we have no influence.

I intend to make a PR this week implementing the support for both `<1.0` and `>=1.0` as I described above (conditional aliasing), keeping in mind that this would only be temporary. Please let me know if you have any remarks regarding that plan or the future deprecation of Locust <1.0 in Transformer.

**Comment by thilp** [comment]
@TimSC I have published [a pre-release](https://github.com/zalando-incubator/transformer/releases/tag/v1.3.0a1), also available on PyPI (`pip install har-transformer==1.3.0a1`). Could you please try it out with your example and report whether it works well in your use-cases too? If it does, I'll ask for review on #71, which will open the door for a general 1.3.0 release supporting both major versions of Locust. Thanks a lot! 😊

**Comment by TimSC** [comment]
@thilp Yes, using transformer==1.3.0a1 to do the conversion works on both locust 0.14.6 and 1.0.3 thanks!

**Comment by TimSC** [comment]
Oops perhaps not...
```[2020-06-05 14:52:46,828] helium/ERROR/locust.user.task: Cannot choose from an empty sequence
Traceback (most recent call last):
  File "/home/tim/dev/qbrio-load/venv/lib/python3.6/site-packages/locust/user/task.py", line 280, in run
    self.schedule_task(self.get_next_task())
  File "/home/tim/dev/qbrio-load/venv/lib/python3.6/site-packages/locust/user/task.py", line 408, in get_next_task
    return random.choice(self.user.tasks)
  File "/usr/lib/python3.6/random.py", line 260, in choice
    raise IndexError('Cannot choose from an empty sequence') from None
IndexError: Cannot choose from an empty sequence```

**Comment by thilp** [comment]
After waiting a bit in case you or someone else found bugs in the pre-release, we just released Transformer 1.3.0 with support for all current major versions of Locust. (It's just an official release of the same pre-release you tried.) Thanks a lot for your help in this @TimSC!
